### ISSUE TITLE
Use IntersectionObserver to detect whether maps are in view

### ISSUE THREAD

**Issue by kamataryo** [tilecloud/embed#24]
https://github.com/w3c/IntersectionObserver/tree/master/polyfill

**Comment by miya0001** [comment]
I hope #25 will be solved with this. 😊

**Comment by miya0001** [comment]
I think, If we can't solve #25 , we need to add option to disable lazy loading.

**Comment by miya0001** [comment]
Fixed at https://github.com/tilecloud/embed/pull/36
